# 服务端口
server:
  port: 8081
# 连接数据库的配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall_ams?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

# 日志的显示级别
logging:
  level:
    com.xiwang.csmall: trace

# 自定义配置
csmall:
  jwt:
    secret-key: kns439a}fdLK34jsmfd{MF5-8DJSsLKhJNFDSjn
    duration-in-minute: 14400