# 激活Profile配置
spring:
  profiles:
    active: dev
  jackson:
  # JSON结果中是否包含为null的属性的默认配置
    default-property-inclusion: non_null


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

knife4j:
  enable: true